FROM ghcr.io/lazear/sage:latest

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends time && \
    rm -rf /var/lib/apt/lists/*

# Replace this with the original user's name
USER sage

WORKDIR /opt/msfragger

CMD ["sage"]
