# -------------------------------------------------------------------
# Stage 1: Clone the repository
# -------------------------------------------------------------------
FROM alpine/git:latest AS repo

WORKDIR /src

RUN git clone --depth 1 https://github.com/MannLabs/alphadia .

FROM ubuntu:22.04 AS tool-provider

# Install time and prepare clean binaries
RUN apt-get update && apt-get install -y --no-install-recommends \
    time \
    && rm -rf /var/lib/apt/lists/*


# -------------------------------------------------------------------
# Stage 2: Application image
# -------------------------------------------------------------------
FROM mosthege/pythonnet:python3.11.2-mono6.12-pythonnet3.0.1

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

#ARG UID=10001

#RUN adduser \
#    --disabled-password \
#    --gecos "" \
#    --home "/home/alphadiauser" \
#    --shell "/sbin/nologin" \
#    --uid "${UID}" \
#    alphadiauser

# Copy the repository from the first stage
COPY --from=repo /src/pyproject.toml pyproject.toml
COPY --from=repo /src/docs docs
COPY --from=repo /src/gui gui
COPY --from=repo /src/requirements requirements
COPY --from=repo /src/alphadia alphadia
COPY --from=repo /src/MANIFEST.in MANIFEST.in


RUN pip install --no-cache-dir ".[stable]"

COPY --from=tool-provider /usr/bin/time /usr/bin/time
COPY --from=tool-provider /lib/*-linux-gnu*/ /lib/

#USER alphadiauser

CMD ["alphadia", "--config", "/app/data/config/config.yaml"]
