FROM debian:bullseye AS tool-provider

RUN apt-get update && \
    apt-get install -y --no-install-recommends time && \
    rm -rf /var/lib/apt/lists/*


FROM ghcr.io/lazear/sage:latest

COPY --from=tool-provider /usr/bin/time /usr/bin/time

WORKDIR /opt/msfragger

CMD ["sage"]
