"""
Canonical silver-layer data model.

Every parquet generated by the platform should conform to one
of the schemas defined in this file.

The schemas are intentionally represented as plain dictionaries
to avoid locking the project into a specific dataframe framework.

This should be pasted into code to comply with the structure,
they are kept here as a reference for future modules that
require access to silver storage.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Column:
    name: str
    dtype: str
    nullable: bool = True


#
# ------------------------------------------------------------------
# 01 Repository scrape
# ------------------------------------------------------------------
#

REPOSITORY_SCHEMA = {
    "table": "repositories",
    "description": "Repository inventory",
    "columns": [
        Column("id", "string", False),
        Column("url", "string", False),
        Column("doi", "string", False)
    ],
}


FILES_SCHEMA = {
    "table": "files",
    "description": "Discovered repository files",
    "columns": [
        Column("id", "string"),
        Column("repository_id", "string", False),
        Column("remote_path", "string", False),
        Column("size_bytes", "int64"),
        Column("scan_timestamp", "timestamp"),
    ],
}

#
# ------------------------------------------------------------------
# Batch Split for labeled dataset <true total dataset with batchs for downstream work
# ------------------------------------------------------------------
#

REPLICATES_SCHEMA = {
    "table": "replicates",
    "description": "Input dataset",
    "columns": [
        Column("id", "string", False),
        Column("organism", "string", False),
        Column("source_type", "string", False),
        Column("material", "string", False),
        Column("condition", "string", False),
        Column("sample_group", "string", False),
    ],
}

#
# ------------------------------------------------------------------
# Local bronze load from remote
# ------------------------------------------------------------------
#

DATASET_SCHEMA = {
    "table": "bronze",
    "description": "Dataset ingest manifest",
    "columns": [
        Column("id", "string", False),
        Column("path", "string"),
        Column("size_bytes", "int64"),
        Column("created_at", "timestamp"),
    ],
}

#
# ------------------------------------------------------------------
# Ingest Bronze
# ------------------------------------------------------------------
#

BRONZE_DATASET_SCHEMA = {
    "table": "bronze_run",
    "description": "Normalized artifact metadata",
    "columns": [
        Column("dataset_id", "string", False),
        Column("bronze_path", "string", False),
        Column("format", "string"),
        Column("compression", "string"),
        Column("row_count", "int64"),
        Column("column_count", "int32"),
        Column("size_bytes", "int64"),
        Column("checksum", "string"),
        Column("created_at", "timestamp"),
        Column("metadata_json", "string"),
    ],
}


BRONZE_MS1_SCHEMA = {
    "table": "bronze_ms1",
    "description": "Column-level metadata",
    "columns": [
        Column("dataset_id", "string", False),
        Column("column_name", "string", False),
        Column("ordinal_position", "int32"),
        Column("logical_type", "string"),
        Column("physical_type", "string"),
        Column("nullable", "bool"),
        Column("distinct_count", "int64"),
        Column("null_count", "int64"),
    ],
}


BRONZE_MS2_SCHEMA = {
    "table": "bronze_ms2",
    "description": "Dataset profiling statistics",
    "columns": [
        Column("dataset_id", "string", False),
        Column("metric_name", "string", False),
        Column("metric_value", "string"),
        Column("metric_type", "string"),
        Column("computed_at", "timestamp"),
    ],
}

#
# ------------------------------------------------------------------
# Dump
# ------------------------------------------------------------------
#

DUMP_REQUEST_SCHEMA = {
    "table": "dump_requests",
    "description": "User dump request",
    "columns": [
        Column("request_id", "string", False),
        Column("request_timestamp", "timestamp"),
        Column("target_tables", "string"),
        Column("filters", "string"),
        Column("output_format", "string"),
    ],
}

#
# ------------------------------------------------------------------
# Registry
# ------------------------------------------------------------------
#

ALL_SCHEMAS = {
    "repositories": REPOSITORY_SCHEMA,
    "files": FILES_SCHEMA,
    "repository_summary": REPOSITORY_SUMMARY_SCHEMA,
    "batch_requests": BATCH_SCHEMA,
    "datasets": DATASET_SCHEMA,
    "bronze_dataset": BRONZE_DATASET_SCHEMA,
    "bronze_ms1": BRONZE_MS1_SCHEMA,
    "bronze_ms2": BRONZE_MS2_SCHEMA,
    "dump_requests": DUMP_REQUEST_SCHEMA,
}
